#nome do workflow
name: Meu primeiro Workflow

#evento ou seja quando ele entra em execução
on: workflow_dispatch

#especificando jobs para esse workflow
jobs:
  #nome do primeiro job
  primeiro_job:
    #runner do primeiro job
    runs-on: ubuntu-latest
    steps:
      #primeiro step
      - name: Hello Github Actions
        run: echo "Hello, github actions"
      #segundo step
      - name: Qual o diretorio atual?
        run: pwd
      #terceiro step
      - name: Qual o conteudo do diretorio, incluido arquivos ocultos?
        run: ls -a
      #quarto step
      - name: até mais!
        run: |
          echo "see you, github actions!"
          echo "bye"
          echo "bye yet again"
      
      
      
      
      
